### ISSUE TITLE
Support for java 21 and Spring-Boot 3.4.0

### ISSUE THREAD

**Issue by matankila** [Hillelmed/bitbucket-client#4]
Hey, 

The code here is has some old version libs. which are not safe anymore, moreover we cannot upgrade our code to java21 & SpringBoot  3.4.0

thanks (from Roy) ♥

**Comment by talantiarun** [comment]
Can i help you?

**Comment by Hillelmed** [comment]
Hey I will update until 1.1.25 the library 
And contribute with love ❤️💪

**Comment by Hillelmed** [comment]
Hey i just released a new version 2.0.0 u can fetch it :)

Enjoy

https://central.sonatype.com/artifact/io.github.hillelmed/bitbucket-client
<dependency>
    <groupId>io.github.hillelmed</groupId>
    <artifactId>bitbucket-client</artifactId>
    <version>2.0.0</version>
</dependency>
